/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example.app

import org.springframework.boot.autoconfigure.SpringBootApplication
import org.springframework.boot.runApplication


@SpringBootApplication
class App

fun main() {
    runApplication<App>()
    listOf(1, 2, 3).forEach { println(it) }
}
